from pathlib import Path

SECTION = r'''<section class="card" id="components">
  <p class="phase">Bill of materials</p>
  <h2>All Azure components for this project</h2>
  <p>You do not provision this list on day one. You grow it in the same order the system itself depends on: a place to run, then a way to change rules and hide secrets, then the two stores on the hot path, then a log that never lies about propensity, then overnight training, and only then a public door. Every database, cache, and log that holds shopper or decision data is created in Canada Central. When you connect these services, you change adapters under <code>services/</code>. You do not rewrite the causal model or the bandit.</p>
  <h3>Foundation</h3>
  <p>Start with a dedicated development subscription and the Entra directory that comes with it. That subscription is the billing and permission root; production pricing data should never live in a personal account. Sign in with <code>az login</code> and confirm you have Contributor. People use Entra to open the portal and the CLI; the Container App later uses a managed identity in the same directory so GitHub never holds a long-lived client secret. Create one resource group in Canada Central and put everything for this environment inside it, because deleting that group is how you stop paying. On the same day, set a Cost Management budget that emails you at a modest cap. A budget warns; it does not always shut resources off. Finally create a single Log Analytics workspace for the environment. Container Apps, App Insights, and later APIM should all write there. Several workspaces make simple questions impossible to ask.</p>
  <h3>Hosting</h3>
  <p>Azure Container Registry is the private shelf for Docker images of this app. Names are globally unique. Basic SKU is enough in development; production can move to Standard or Premium and, later, a replica in Canada East. A Container Apps environment is the cluster those images join, and you attach Log Analytics when you create it. The Container App itself is this FastAPI process: stages 0 through 10, a small CPU and memory footprint at first, replicas when traffic grows, and revisions so a new policy can take one percent of calls without replacing the old one. In development ingress can be external so you can open a browser; in production it should be internal behind API Management, and <code>/v1/price:explain</code>, <code>/v1/control</code>, and admin reload must never be on the public product. A Container Apps Job is the same codebase on a schedule for campaign lists. Do not fire thousands of single HTTP calls from Logic Apps with no backpressure. Do not begin on AKS or App Service. Container Apps is the host until you have a platform team and a scale problem that revisions cannot solve.</p>
  <h3>Config and secrets</h3>
  <p>Give the Container App a system-assigned managed identity and grant that identity roles, rather than baking Cosmos or Redis keys into environment variables. Key Vault holds the remaining secrets: Redis URL, Event Hubs send string, App Insights connection string, Cosmos key until you switch the SDK to Entra. Use RBAC on the vault, not a mix of access policies. App Configuration is the live rulebook that used to be <code>control_plane.yaml</code> and <code>versions.yaml</code>: kill switch, merchandiser freeze, policy and model pins, daily discount budget. Those flags must refresh in seconds. If App Configuration cannot be read, fail closed to list price using a cache no older than a minute. Free SKU is fine in development; production wants Standard and a replica in Canada East.</p>
  <h3>Online data plane</h3>
  <p>Two stores sit on the request. Redis, on TLS port 6380, is the millisecond cache that replaces the in-memory feature store and sticky-price map. Keys are short-lived: features, a sticky offer for shopper and SKU, frequency caps, and an incremented discount budget. If Redis is unavailable you still return a price from coarser defaults, because checkout cannot wait. Basic C0 is enough to learn the adapter; production should be Premium, zone redundant, and private. Cosmos DB is the system of record that replaces <code>catalog.yaml</code>, identity profiles, the coupon list, and decision lookup. Use separate containers partitioned on sku, customer_id, offer code, and customer_id again for decisions. Serverless is the right development SKU. Production should autoscale, back up, and fail over to Canada East. A coupon in Cosmos is a promise: a later policy change must not void a code already shown.</p>
  <h3>Streaming and lakehouse</h3>
  <p>Decision logs are telemetry, not a command queue, which is why Event Hubs with Kafka enabled replaces the JSONL buffer and Service Bus does not. One hub, <code>pricing.decisions.v1</code>, receives every <code>decide()</code> with propensity, policy id, candidate-set version, and experiment variant. Another, <code>pricing.outcomes.v1</code>, receives purchase, refund, and return keyed by <code>decision_id</code>, joined later on a seven-day window net of refunds. Joining only on customer_id will mix people and ruin OPE. Schema Registry versions that JSON so a silent field drop cannot poison training. ADLS Gen2 with hierarchical namespace is the lake: bronze for raw capture, silver for joined point-in-time rows, gold for OPE and campaigns. A plain blob account without HNS will fight Spark. Event Hubs Capture writes bronze on a timer so you do not need a custom consumer on day one. Keep capture in the same region. If the hub is down, buffer locally and stop exploring until it returns, or the propensities you log will be fiction.</p>
  <h3>Machine learning</h3>
  <p>Training never runs inside the online Container App. Azure ML is the workspace that replaces <code>data/registry/models.json</code> and laptop jobs: you submit causal, bandit, and OPE work, keep lineage, and register a model only when OPE beats the current policy and fairness and drift are acceptable. Serverless compute is enough for the numpy learners in this repo. A GPU cluster is a later choice and a common way to leave money running overnight. When joins no longer fit a single node, Microsoft Fabric or Azure Databricks in Canada Central reads the same ADLS paths that <code>offline/join.py</code> and <code>backfill.py</code> use today. The standing risk is training on “current” features instead of the values as of the decision timestamp.</p>
  <h3>Public edge</h3>
  <p>Skip Front Door and API Management until a real channel is calling you. Then Front Door Premium is the anycast door with TLS, bot manager, origin health, and a Canada POP. Point it at APIM or the app, never at the explain endpoint. Put the WAF in Detection for a week, then Prevention, with an allowlist for partner IPs. API Management is the product split that used to live in <code>gateway.py</code>: public price, checkout outcomes, CS lookup, and an internal product for explain and control. Developer SKU has no SLA; production should be Standard v2 or Premium on a VNet.</p>
  <h3>Observability and rollback</h3>
  <p>A bandit you cannot measure is just random prices. Application Insights, created against the same Log Analytics workspace, replaces in-process counters for production: duration of <code>/v1/price</code>, calls out to Redis and Cosmos, exceptions. Do not log propensity or PII in custom events; <code>decision_id</code> is enough on the public path. Metric alerts and an action group with a named owner fire on slow p99, 5xx, a gap between requests and Event Hub ingress, a stale kill switch, or a fairness gap. A workbook later fills the role of the lab Monitor tab: reward versus predicted value, propensity PSI, segment price gaps, logging completeness. Sampled telemetry makes those charts lie.</p>
  <h3>Security and Canada</h3>
  <p>In production, Redis, Cosmos, Key Vault, Storage, and Event Hubs should not have public endpoints. A VNet, private endpoints, and Container Apps integration are required, and DNS must be in place or the app will hang on names. Purview scans ADLS, classifies PII, and is how you show PIPEDA evidence that bronze decisions are not a free-for-all. Protected attributes used for audit must never enter the feature vector. Defender for Cloud watches for a public Cosmos account, Redis without TLS, and vulnerable images in ACR. Do not ship an image the registry has already flagged.</p>
  <h3>CI/CD</h3>
  <p>GitHub Actions with Entra OIDC is how a commit becomes a revision: tests, image, push to ACR, Container Apps update. Failed pytest must not deploy. Do not put <code>AZURE_CLIENT_SECRET</code> in GitHub. Federate the app registration and use <code>azure/login</code> with the federated token.</p>
  <h3>What to leave alone</h3>
  <p>AKS is a later host if Container Apps and a platform team cannot meet a sustained ten thousand decisions a second with a mesh you truly need. App Service slots are not a substitute for a propensity-logged canary. Service Bus is fine for occasional commands, not for this telemetry. Azure Communication Services is optional if you have no email provider; even then, never send a price that is not already in the offer ledger.</p>
  <label class="step"><input type="checkbox" data-k="all-components" /><span>I have read this as a sequence, not a shopping cart, and I will not start on AKS or Service Bus.</span></label>
</section>
'''

html_path = Path("docs/azure-implementation.html")
html = html_path.read_text(encoding="utf-8")
start = html.find('<section class="card" id="components">')
end = html.find('<section class="card" id="picture">')
if start < 0 or end < 0:
    raise SystemExit(f"markers missing {start} {end}")
html_path.write_text(html[:start] + SECTION.strip() + "\n\n" + html[end:], encoding="utf-8")
print("ok")
